### ISSUE TITLE
2022.1: Circular dependency with django-crispy-forms

### ISSUE THREAD

**Issue by dvzrv** [django-crispy-forms/crispy-bootstrap3#3]
Hi! Similar to what is discussed in https://github.com/django-crispy-forms/crispy-bootstrap4/issues/7 I think that this project should also not require django or django-crispy-forms, as that creates a dependency loop which is particularly bad for bootstrap scenarioes.

Both dependencies are only required during testing. The django-crispy-forms project on the other hand should require crispy-bootstrap3 and crispy-bootstrap4.

**Comment by smithdc1** [comment]
As per the linked issue ill close this for now. Happy to re-open if someone can help me understand the issue. Or even better open a PR with a proposed fix and tests.
